### ISSUE TITLE
How to obtain the belongs.npy

### ISSUE THREAD

**Issue by JaywongWang** [Tsingularity/youtube-8m#1]
Hi,

Do you mind uploading belongs.npy or can you explain how to  obtain this file (contains correspondence between coarse labels and fine labels, I guess)?

Thank you.

by Jingwen

**Comment by Tsingularity** [comment]
Hi Jingwen,

Thanks for your interest and I am really sorry for the late reply. It was not until now I started to notice this message when I organized and clean my old repos.

I think it might be impossible for me now to upload the belongs.npy because I totally don't have the code after I finished my internship at SenseTime. And apologies for not uploading that file. I think it was not included in git by accident because I remembered I intend to upload everything that was necessary for reproducing our experiments.

For how to obtain this file, I remember it was actually pretty straightforward. I remember there was a class hierarchy file on the official youtube8M website, which was the one we used to obtain belongs.npy.

Hope this helps but I guess this is way too late.

Just let me know if there's anything else I can help.
